[toolchain]
anchor_version = "0.32.1"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
billion = "BDBCR33yBuWjGJiGXoApW3qR9ajP2fGSJfzTP6SbYn6h"

[programs.localnet]
billion = "B2qM4b8cT31jwT3rwhEpXDRKP7gVypzWdixcFPEgdvNW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""

[test]
startup_wait = 60000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
dynamic_port_range = "18001-18100"
gossip_port = 18000
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d"
